services:
  app:
    container_name: Xue
    build: .
    volumes:
      - ./data:/app/data
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock